### ISSUE TITLE
A little simplification for noob?

### ISSUE THREAD

**Issue by sgaurav510** [abhibalani/tinder-bot-python#1]
can you provide a ready made script in which we have to login and then run the script

**Comment by iabhishekbalani** [comment]
> can you provide a ready made script in which we have to login and then run the script

That's what I have done in this repository. Please read the readme file.

**Comment by sgaurav510** [comment]
[Running] python -u "c:\Users\sgaur\Downloads\tinder-bot-python-master\tinder-bot-python-master\tinder_bot.py"
c:\Users\sgaur\Downloads\tinder-bot-python-master\tinder-bot-python-master\tinder_bot.py:37: DeprecationWarning: use options instead of chrome_options
  self.driver = webdriver.Chrome(
Traceback (most recent call last):
  File "c:\Users\sgaur\Downloads\tinder-bot-python-master\tinder-bot-python-master\tinder_bot.py", line 98, in <module>
    tinder_bot = TinderBot()
  File "c:\Users\sgaur\Downloads\tinder-bot-python-master\tinder-bot-python-master\tinder_bot.py", line 37, in __init__
    self.driver = webdriver.Chrome(
  File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory


[Done] exited with code=1 in 3.469 seconds

any help?

**Comment by iabhishekbalani** [comment]
> [Running] python -u "c:\Users\sgaur\Downloads\tinder-bot-python-master\tinder-bot-python-master\tinder_bot.py"
> c:\Users\sgaur\Downloads\tinder-bot-python-master\tinder-bot-python-master\tinder_bot.py:37: DeprecationWarning: use options instead of chrome_options
> self.driver = webdriver.Chrome(
> Traceback (most recent call last):
> File "c:\Users\sgaur\Downloads\tinder-bot-python-master\tinder-bot-python-master\tinder_bot.py", line 98, in
> tinder_bot = TinderBot()
> File "c:\Users\sgaur\Downloads\tinder-bot-python-master\tinder-bot-python-master\tinder_bot.py", line 37, in **init**
> self.driver = webdriver.Chrome(
> File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in **init**
> RemoteWebDriver.**init**(
> File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Users\sgaur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory
> 
> [Done] exited with code=1 in 3.469 seconds
> 
> any help?

You can try replacing (double quotes)
`        # This will create a new profile in your chrome browser
        chrome_options.add_argument(
            "--user-data-dir=C:\\Users\\username\\AppData\\Local\\Google Selenium\\Chrome\\User Data"
        )
        chrome_options.add_argument(
            "--profile-directory=Default"
        )`
with (single quotes)
`        # This will create a new profile in your chrome browser
        chrome_options.add_argument(
            '--user-data-dir=C:\\Users\\username\\AppData\\Local\\Google Selenium\\Chrome\\User Data'
        )
        chrome_options.add_argument(
            '--profile-directory=Default'
        )`

**Comment by sgaurav510** [comment]
still the same error. is there anywhere i can contact you like telegram id or something where you can assist me or help me using TeamViewer or any desk
